AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  boardgames-sam-api

  SAM Template for Boardgames SAM API

Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,Calisaurus-User,Calisaurus-User-Api-Key'"
      AllowOrigin: "'*'"
Resources:
  BoardgamesApiTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: boardgames-api
Outputs:
  BoardgamesSamApi:
    Description: "API Gateway endpoint URL for Prod stage of Boardgames SAM API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/summary/"
