AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SummaryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: boardgame-summary/
      Handler: app.summaryHandler
      Runtime: nodejs14.x
      Events:
        Summary:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /summary
            Method: get
  SummaryByYearFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: boardgame-summary/
      Handler: app.summaryByYearHandler
      Runtime: nodejs14.x
      Events:
        Summary:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /summary/{year}
            Method: get
  PlayDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: boardgame-summary/
      Handler: app.playDataHandler
      Runtime: nodejs14.x
      Policies: 
        - S3FullAccessPolicy:
            BucketName: boardgames-tracking
      Events:
        Summary:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /createPlayRecord
            Method: post
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SummaryApi:
    Description: "API Gateway endpoint URL for Prod stage for Summary function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/summary/"
  SummaryFunction:
    Description: "Summary Lambda Function ARN"
    Value: !GetAtt SummaryFunction.Arn
  SummaryFunctionIamRole:
    Description: "Implicit IAM Role created for Summary function"
    Value: !GetAtt SummaryFunctionRole.Arn
  PlayDataFunction:
    Description: "PlayDataFunction Lambda Function ARN"
    Value: !GetAtt PlayDataFunction.Arn
  PlayDataFunctionIamRole:
    Description: "Implicit IAM Role created for Play Data function"
    Value: !GetAtt PlayDataFunctionRole.Arn
