AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: |
  boardgames-sam-api
  SAM Template for Boardgames SAM API
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: '''DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'''
      AllowHeaders: '''Content-Type'''
      AllowOrigin: '''*'''
Resources:
  StatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api-code/
      Handler: app.statusHandler
      Runtime: nodejs14.x
      Events:
        Summary:
          Type: Api
          Properties:
            Path: /status
            Method: GET
  CreatePlayRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api-code/
      Handler: app.createPlayRecordHandler
      Runtime: nodejs14.x
      Events:
        Summary:
          Type: Api
          Properties:
            Path: /createPlayRecord
            Method: POST
Outputs:
  BoardgamesSamApi:
    Description: API Gateway endpoint URL for Prod stage of Boardgames SAM API
    Value: !Sub >-
      https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/summary/
  StatusFunction:
    Description: Status Lambda Function ARN
    Value: !GetAtt StatusFunction.Arn
  StatusFunctionIamRole:
    Description: Implicit IAM Role created for Status function
    Value: !GetAtt StatusFunctionRole.Arn
  CreatePlayRecordFunction:
    Description: CreatePlayRecord Lambda Function ARN
    Value: !GetAtt CreatePlayRecordFunction.Arn
  CreatePlayRecordFunctionIamRole:
    Description: Implicit IAM Role created for CreatePlayRecord function
    Value: !GetAtt CreatePlayRecordFunctionRole.Arn
