AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  boardgames-sam-api

  SAM Template for Boardgames SAM API
  
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  StatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api-code/
      Handler: app.statusHandler
      Runtime: nodejs14.x
      Events:
        Summary:
          Type: Api
          Properties:
            Path: /status
            Method: get
  PlayDataFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: api-code/
      Handler: app.playDataHandler
      Runtime: nodejs14.x
      Policies: 
        - S3FullAccessPolicy:
            BucketName: boardgames-tracking
      Events:
        Summary:
          Type: Api 
          Properties:
            Path: /createPlayRecord
            Method: post
Outputs:
  BoardgamesSamApi:
    Description: "API Gateway endpoint URL for Prod stage of Boardgames SAM API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/summary/"
  StatusFunction:
    Description: "Summary Lambda Function ARN"
    Value: !GetAtt StatusFunction.Arn
  StatusFunctionIamRole:
    Description: "Implicit IAM Role created for Status function"
    Value: !GetAtt StatusFunctionRole.Arn
  PlayDataFunction:
    Description: "PlayDataFunction Lambda Function ARN"
    Value: !GetAtt PlayDataFunction.Arn
  PlayDataFunctionIamRole:
    Description: "Implicit IAM Role created for Play Data function"
    Value: !GetAtt PlayDataFunctionRole.Arn
