on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1

      - name: Use Node JS LTS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install npm dependencies
        working-directory: ./api-code
        run: npm install

      - name: Run build steps
        working-directory: ./api-code
        run: npm build -s

      - name: Run default tests
        working-directory: ./api-code
        run: npm test -s
        
      - name: SAM Build
        run: sam build --use-container

      - name: Register Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: SAM Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset