name: Deploy to AWS
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Use Node JS LTS
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install npm dependencies
        run: npm install

      - name: Install npm dependencies
        working-directory: ./api-code
        run: npm install

      - name: Run build steps
        run: npm run build -s
        env:
          CURRENT_BRANCH: ${{ github.ref }}

      - name: Run default tests
        working-directory: ./api-code
        run: npm test -s
        env:
          CURRENT_BRANCH: ${{ github.ref }}
        
      - name: Register Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: SAM Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
